blank_issues_enabled: false
contact_links:
  - name: Website
    url: https://bliss-bass.github.io
    about: 'Bliss Bass Website'
  - name: Documentation
    url: https://docs.blisscolabs.dev
    about: 'Bliss Bass Documentation'
  - name: Help
    url: https://t.me/navotpala/
    about: 'If you need further assistance, join our community.'
