# /data/misc/settings_secure.conf
# Global Android secure settings configuration for vendor_ax86-lite.
# Lines starting with '#' or empty lines are ignored.

# Input Method
default_input_method=com.android.inputmethod.latin/.LatinIME

# Notifications on lock screen
lock_screen_show_notifications=1